djaime23/applications/personas/urls.py
from django.urls import path
from . import views 

app_name = "persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todos-empleados/', views.LisAllEmpleados.as_view(), name='empleados_all'),
    path('list-by-area/<subnombre>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadoBykword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmplado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleados_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

djaime23/empleado/urls.py
"""
URL configuration for empleado project.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # EL ORDEN IMPORTA: personas primero porque tiene path ''
    path('', include('applications.personas.urls')),
    # departamento con prefijo para evitar conflictos
    path('departamento/', include('applications.departamento.urls')),
    # home al final
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djaime23/applications/personas/models.py
from django.db import models
from ckeditor.fields import RichTextField
from applications.departamento.models import Departamento
# Create your models here.

class Habilidades(models.Model):
    habilidad=models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name='Habilidad'
        verbose_name_plural='Habilidades Empleados'

    def __str__(self):
        return str(self.id)+ '-'+ self.habilidad



class Empleado(models.Model):

    JOB_CHOICES=[ ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
        ]
       
    # CORREGIDO: firts_name -> first_name
    first_name = models.CharField('Nombre', max_length=60)  # CORREGIDO
    last_name= models.CharField('Apellido', max_length=60)
    full_name=models.CharField(
        'Nombres Completos',
        max_length=120,
        blank=True
    )

    job = models.CharField('Trabajo',max_length=50,choices=JOB_CHOICES,default='3')
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades=models.ManyToManyField(Habilidades)
    hoja_vida=RichTextField() 

    class Meta:
        verbose_name='Mi Empleado'
        verbose_name_plural='Empleados de la empresa'
        # CORREGIDO: firts_name -> first_name
        ordering=['-first_name','last_name']  # CORREGIDO
        # CORREGIDO: firts_name -> first_name
        unique_together=('first_name','departamento')  # CORREGIDO

    def __str__(self):
        # CORREGIDO: firts_name -> first_name
        return str(self.id)+ '-'+ self.first_name +'-' + self.last_name  # CORREGIDO

djaime23/applications/personas/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields=[
            'first_name',  # CORREGIDO
            'last_name',
            'job', 
            'departamento',
            'habilidades',
            'avatar'
        ]
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

djaime23/applications/personas/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)
#models
from .models import Empleado
# forms
from .forms import EmpleadoForm

class InicioView(TemplateView):
    """ Vista que carga página de inicio """
    template_name = 'inicio.html'

class ListaEmpleadosAdmin(ListView):
    template_name='persona/lista_empleados.html'
    paginate_by= 7
    ordering='first_name'  # CORREGIDO
    context_object_name='empleados'
    model=Empleado


class LisAllEmpleados(ListView):
    template_name='persona/list_all.html'
    paginate_by= 7
    ordering='first_name'  # CORREGIDO
    context_object_name='empleados'

    def get_queryset(self):
        palabra_clave=self.request.GET.get("kword",'')
        lista=Empleado.objects.filter(
            full_name__icontains=palabra_clave
            )
        return lista

class ListByAreaEmpleado(ListView):
    """Lista empleados de un area"""
    template_name='persona/list_by_area.html'
    context_object_name='empleados'
   

    def get_queryset(self):
       area=self.kwargs['subnombre']
       lista=Empleado.objects.filter(
           departamento__subnombre=area
       )   
       return lista

class ListEmpleadoBykword(ListView):
    """Lista de empleado por palabra clave"""
    template_name='persona/by_kword.html'
    context_object_name='empleados'
    
    def get_queryset(self):
        print('*************************')
        palabra_clave=self.request.GET.get("kword",'')
        #print('=================',palabra_clave)
        lista=Empleado.objects.filter(first_name=palabra_clave)  # CORREGIDO
        return lista
    
class ListHabilidadesEmplado(ListView):
    template_name='persona/habilidades.html'
    context_object_name='habilidades'

    def get_queryset(self):
        empleado=Empleado.objects.get(id=1)
        return empleado.habilidades.all()
    
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context
    
class SuccessView(TemplateView):
    template_name = "persona/success.html"

class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url=reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        #logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name  # CORREGIDO
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)
    

class EmpleadoUdateView(UpdateView):
    template_name="persona/update.html"
    model= Empleado
    fields=[
        'first_name',  # CORREGIDO
        'last_name',
        'full_name',
        'job', 
        'departamento',
        'habilidades'
        ]
    success_url=reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('#############METODO POST ###################3')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        print('****metodo form valid *******')
        self.object = form.save()
        return super(EmpleadoUdateView, self).form_valid(form)

class EmpleadoDeleteView(DeleteView):
    model=Empleado
    template_name="persona/delete.html"
    success_url=reverse_lazy('persona_app:empleados_admin')

djaime23/templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
    Registar Empleado
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registar Empleado</h1>    
    <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="medium-6 cell">
            <label>Nombre:
            {{ form.first_name }}  <!-- CORREGIDO -->
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Apellidos:
            {{ form.last_name }}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Trabajo:
            {{ form.job }}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Area:
            {{ form.departamento }}
            </label>
        </div>
        <div class="medium-6 cell">
            <label>Habilidades:
            {{ form.habilidades }}
            </label>
        </div>
        <div class="medium-12 cell">
            <label>Foto:
            {{ form.avatar }}
            </label>
        </div>
        <div class="medium-12 cell">
            <button type="submit" class="button success">Agregar</button>
        </div>
    </form>
    </div>
</div>
{% endblock content %}

djaime23/templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aki">
    <button type="submit">Buscar</button>

<h3>Lista de resultados</h3>

<u>
    {% for e in empleados %}
        <li>
            {{ e }}
        </li>
    {% endfor %}
</u>

</form>

djaime23/templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
    Edita Empleado
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.firts_name }} {{ object.last_name }}</h1>
        
        <form class="cell" method="POST"> {% csrf_token %}

        <div class="callout secondary">
            <h5>¿Confirme que desea eliminar?</h5>
            <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

djaime23/templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ object.full_name }}
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
      <div class="card-divider">
        {{ empleado.get_job_display }}
      </div>
      {% if empleado.avatar %}
          <img src="{{ empleado.avatar.url }}">
      {% else %}
          <img src="{% static 'img/ima1.jpg' %}">
      {% endif %}

      <div class="card-section">
        <h4>{{ empleado.full_name }}</h4>
        <p>{{ empleado.last_name }}</p>
        <p>{{ empleado.departamento.shor_name }}</p>
        <p><span class="label">Habilidades:</span></p>
        <ul class="vertical menu">
          {% for h in empleado.habilidades.all %}
          <li>{{ h.habilidad }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

djaime23/templates/persona/habilidades.html
<h1>Habilidades de empleado</h1>

<ul>

    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
</ul>

djaime23/templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="150">ID</th>
                        <th width="150">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name }}</td>  <!-- CORREGIDO -->
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                    </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %}
                        <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                        <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

djaime23/templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    Lista empleados por departamento
{% endblock title %}


{% block content %}
      {% include "includes/header.html" %}
      <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area:</div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="150">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empleado in empleados %}
                        <tr>
                            <td>{{ empleado.id }}</td>
                            <td>{{ empleado.firts_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento }}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.id %}">Ver</a></td>
                        </tr>
                         {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
      </div>
{% endblock content %}

<h1>Lista de todos de los empleados</h1>

<ul>
    {% for e in object_list %}
        <li>
            {{ e }}
        </li>
    {% endfor %}
</ul>

djaime23/templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="150">ID</th>
                        <th width="150">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name }}</td>  <!-- CORREGIDO -->
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td><a class="button success" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a></td>
                        <td><a class="button alert" href="{% url 'persona_app:eliminar_empleado' empleado.id %}">Eliminar</a></td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                    </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                            <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

djaime23/templates/persona/success.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/header.html" %}

<h1>Felicitaciones, se ha guardado correctamente el empleado</h1>
{% endblock content %}

djaime23/templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
    Edita Empleado
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar Empleado</h1>
        <div class="cell">
            <form method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                    {{ form.first_name }}  <!-- CORREGIDO -->
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                    {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                    {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                    {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades Extarnas:
                    {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}