djaime23/applications/departamento/urls.py
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'lista/',
        views.DepartamentoListView.as_view(), 
        name='departamento-list'  # NOMBRE CORREGIDO
    ),
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_departamento'
    ),
]

djaime23/applications/personas/urls.py
from django.urls import path
from . import views 

app_name = "persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todos-empleados/', views.LisAllEmpleados.as_view(), name='empleados_all'),
    path('list-by-area/<subnombre>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadoBykword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmplado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleados_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

djaime23/empleado/urls.py
"""
URL configuration for empleado project.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # EL ORDEN IMPORTA: personas primero porque tiene path ''
    path('', include('applications.personas.urls')),
    # departamento con prefijo para evitar conflictos
    path('departamento/', include('applications.departamento.urls')),
    # home al final
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djaime23/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li>
        <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
      </li>
      <li>
        <a href="{% url 'departamento_app:departamento-list' %}">Departamentos</a>
      </li>
      <li>
        <a href="{% url 'persona_app:empleados_admin' %}">Administrar</a>
      </li>
      <li>
        <a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a>
      </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado"></li>
      <li>
        <a href="{% url 'persona_app:empleados_add' %}" class="button">Registrar Nuevo</a>
      </li>
    </ul>
  </div>
</div>